package au.com.leonardo.poc.sms_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Aircraft implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String aircraftRegistration;
	private java.lang.Integer passengerCapacity_Econ;
	private java.lang.Integer passengerCapacity_Busi;

	public Aircraft() {
	}

	public java.lang.String getAircraftRegistration() {
		return this.aircraftRegistration;
	}

	public void setAircraftRegistration(java.lang.String aircraftRegistration) {
		this.aircraftRegistration = aircraftRegistration;
	}

	public java.lang.Integer getPassengerCapacity_Econ() {
		return this.passengerCapacity_Econ;
	}

	public void setPassengerCapacity_Econ(
			java.lang.Integer passengerCapacity_Econ) {
		this.passengerCapacity_Econ = passengerCapacity_Econ;
	}

	public java.lang.Integer getPassengerCapacity_Busi() {
		return this.passengerCapacity_Busi;
	}

	public void setPassengerCapacity_Busi(
			java.lang.Integer passengerCapacity_Busi) {
		this.passengerCapacity_Busi = passengerCapacity_Busi;
	}

	public Aircraft(java.lang.String aircraftRegistration,
			java.lang.Integer passengerCapacity_Econ,
			java.lang.Integer passengerCapacity_Busi) {
		this.aircraftRegistration = aircraftRegistration;
		this.passengerCapacity_Econ = passengerCapacity_Econ;
		this.passengerCapacity_Busi = passengerCapacity_Busi;
	}

}