package au.com.leonardo.poc.sms_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Event implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String attributeName;
	private java.lang.Boolean hasChanged;
	private java.lang.String lastValue;
	private java.lang.String currentValue;

	public Event() {
	}

	public java.lang.String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(java.lang.String attributeName) {
		this.attributeName = attributeName;
	}

	public java.lang.Boolean getHasChanged() {
		return this.hasChanged;
	}

	public void setHasChanged(java.lang.Boolean hasChanged) {
		this.hasChanged = hasChanged;
	}

	public java.lang.String getLastValue() {
		return this.lastValue;
	}

	public void setLastValue(java.lang.String lastValue) {
		this.lastValue = lastValue;
	}

	public java.lang.String getCurrentValue() {
		return this.currentValue;
	}

	public void setCurrentValue(java.lang.String currentValue) {
		this.currentValue = currentValue;
	}

	public Event(java.lang.String attributeName, java.lang.Boolean hasChanged,
			java.lang.String lastValue, java.lang.String currentValue) {
		this.attributeName = attributeName;
		this.hasChanged = hasChanged;
		this.lastValue = lastValue;
		this.currentValue = currentValue;
	}

}