package au.com.leonardo.poc.sms_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FlightLeg implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String departsFrom;
	private java.lang.String scheduledDepartureTime;
	private java.lang.String arrivesAt;
	private java.lang.String scheduledArrivalTime;

	public FlightLeg() {
	}

	public java.lang.String getDepartsFrom() {
		return this.departsFrom;
	}

	public void setDepartsFrom(java.lang.String departsFrom) {
		this.departsFrom = departsFrom;
	}

	public java.lang.String getScheduledDepartureTime() {
		return this.scheduledDepartureTime;
	}

	public void setScheduledDepartureTime(
			java.lang.String scheduledDepartureTime) {
		this.scheduledDepartureTime = scheduledDepartureTime;
	}

	public java.lang.String getArrivesAt() {
		return this.arrivesAt;
	}

	public void setArrivesAt(java.lang.String arrivesAt) {
		this.arrivesAt = arrivesAt;
	}

	public java.lang.String getScheduledArrivalTime() {
		return this.scheduledArrivalTime;
	}

	public void setScheduledArrivalTime(java.lang.String scheduledArrivalTime) {
		this.scheduledArrivalTime = scheduledArrivalTime;
	}

	public FlightLeg(java.lang.String departsFrom,
			java.lang.String scheduledDepartureTime,
			java.lang.String arrivesAt, java.lang.String scheduledArrivalTime) {
		this.departsFrom = departsFrom;
		this.scheduledDepartureTime = scheduledDepartureTime;
		this.arrivesAt = arrivesAt;
		this.scheduledArrivalTime = scheduledArrivalTime;
	}

}