package au.com.leonardo.poc.sms_test;

import java.math.BigInteger;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Flight implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private BigInteger flightID;
	private java.lang.String flightNumber;
	private java.util.List<au.com.leonardo.poc.sms_test.FlightLeg> flightLegs;
	private java.lang.String aircraftManufacturer;
	private java.lang.String aircraftModel;
	private au.com.leonardo.poc.sms_test.Aircraft aircraft;
	private au.com.leonardo.poc.sms_test.ThisFlight thisFlight;

	public Flight() {
	}

	public java.lang.String getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(java.lang.String flightNumber) {
		this.flightNumber = flightNumber;
	}

	public java.util.List<au.com.leonardo.poc.sms_test.FlightLeg> getFlightLegs() {
		return this.flightLegs;
	}

	public void setFlightLegs(
			java.util.List<au.com.leonardo.poc.sms_test.FlightLeg> flightLegs) {
		this.flightLegs = flightLegs;
	}

	public java.lang.String getAircraftManufacturer() {
		return this.aircraftManufacturer;
	}

	public void setAircraftManufacturer(java.lang.String aircraftManufacturer) {
		this.aircraftManufacturer = aircraftManufacturer;
	}

	public java.lang.String getAircraftModel() {
		return this.aircraftModel;
	}

	public void setAircraftModel(java.lang.String aircraftModel) {
		this.aircraftModel = aircraftModel;
	}

	public au.com.leonardo.poc.sms_test.Aircraft getAircraft() {
		return this.aircraft;
	}

	public void setAircraft(au.com.leonardo.poc.sms_test.Aircraft aircraft) {
		this.aircraft = aircraft;
	}

	public au.com.leonardo.poc.sms_test.ThisFlight getThisFlight() {
		return this.thisFlight;
	}

	public void setThisFlight(au.com.leonardo.poc.sms_test.ThisFlight thisFlight) {
		this.thisFlight = thisFlight;
	}

	public java.math.BigInteger getFlightID() {
		return this.flightID;
	}

	public void setFlightID(java.math.BigInteger flightID) {
		this.flightID = flightID;
	}

	public Flight(java.math.BigInteger flightID, java.lang.String flightNumber,
			java.util.List<au.com.leonardo.poc.sms_test.FlightLeg> flightLegs,
			java.lang.String aircraftManufacturer,
			java.lang.String aircraftModel,
			au.com.leonardo.poc.sms_test.Aircraft aircraft,
			au.com.leonardo.poc.sms_test.ThisFlight thisFlight) {
		this.flightID = flightID;
		this.flightNumber = flightNumber;
		this.flightLegs = flightLegs;
		this.aircraftManufacturer = aircraftManufacturer;
		this.aircraftModel = aircraftModel;
		this.aircraft = aircraft;
		this.thisFlight = thisFlight;
	}

}