package au.com.leonardo.poc.sms_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String messageText;
	private java.lang.String subjectText;
	private java.lang.Boolean isMMS = false;

	public Message() {
	}

	public java.lang.String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(java.lang.String messageText) {
		this.messageText = messageText;
	}

	public java.lang.String getSubjectText() {
		return this.subjectText;
	}

	public void setSubjectText(java.lang.String subjectText) {
		this.subjectText = subjectText;
	}

	public java.lang.Boolean getIsMMS() {
		return this.isMMS;
	}

	public void setIsMMS(java.lang.Boolean isMMS) {
		this.isMMS = isMMS;
	}

	public Message(java.lang.String messageText, java.lang.String subjectText,
			java.lang.Boolean isMMS) {
		this.messageText = messageText;
		this.subjectText = subjectText;
		this.isMMS = isMMS;
	}

}