package au.com.leonardo.poc.sms_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MMSContent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private java.lang.String filename;
	private java.lang.String payload;

	public MMSContent() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getFilename() {
		return this.filename;
	}

	public void setFilename(java.lang.String filename) {
		this.filename = filename;
	}

	public java.lang.String getPayload() {
		return this.payload;
	}

	public void setPayload(java.lang.String payload) {
		this.payload = payload;
	}

	public MMSContent(java.lang.String type, java.lang.String filename,
			java.lang.String payload) {
		this.type = type;
		this.filename = filename;
		this.payload = payload;
	}

}