package au.com.leonardo.poc.sms_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MMSpayload implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String to;
	private java.lang.String from;
	private java.lang.String subject;
	private Boolean replyRequest;

	private java.util.List<au.com.leonardo.poc.sms_test.MMSContent> MMSContent;

	public MMSpayload() {
	}

	public java.lang.String getTo() {
		return this.to;
	}

	public void setTo(java.lang.String to) {
		this.to = to;
	}

	public java.lang.String getFrom() {
		return this.from;
	}

	public void setFrom(java.lang.String from) {
		this.from = from;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.util.List<au.com.leonardo.poc.sms_test.MMSContent> getMMSContent() {
		return this.MMSContent;
	}

	public void setMMSContent(
			java.util.List<au.com.leonardo.poc.sms_test.MMSContent> MMSContent) {
		this.MMSContent = MMSContent;
	}

	public java.lang.Boolean getReplyRequest() {
		return this.replyRequest;
	}

	public void setReplyRequest(java.lang.Boolean replyRequest) {
		this.replyRequest = replyRequest;
	}

	public MMSpayload(java.lang.String to, java.lang.String from,
			java.lang.String subject, java.lang.Boolean replyRequest,
			java.util.List<au.com.leonardo.poc.sms_test.MMSContent> MMSContent) {
		this.to = to;
		this.from = from;
		this.subject = subject;
		this.replyRequest = replyRequest;
		this.MMSContent = MMSContent;
	}

}