package au.com.leonardo.poc.sms_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SMSPayload implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> to;
	private java.lang.String from;
	private java.lang.Integer validity;
	private java.lang.Boolean priority;
	private java.lang.String body;

	public SMSPayload() {
	}

	public java.util.List<java.lang.String> getTo() {
		return this.to;
	}

	public void setTo(java.util.List<java.lang.String> to) {
		this.to = to;
	}

	public java.lang.String getFrom() {
		return this.from;
	}

	public void setFrom(java.lang.String from) {
		this.from = from;
	}

	public java.lang.Integer getValidity() {
		return this.validity;
	}

	public void setValidity(java.lang.Integer validity) {
		this.validity = validity;
	}

	public java.lang.Boolean getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.Boolean priority) {
		this.priority = priority;
	}

	public java.lang.String getBody() {
		return this.body;
	}

	public void setBody(java.lang.String body) {
		this.body = body;
	}

	public SMSPayload(java.util.List<java.lang.String> to,
			java.lang.String from, java.lang.Integer validity,
			java.lang.Boolean priority, java.lang.String body) {
		this.to = to;
		this.from = from;
		this.validity = validity;
		this.priority = priority;
		this.body = body;
	}

}