package au.com.leonardo.poc.sms_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ThisFlight implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer passengerSouls_Econ;
	private java.lang.Integer passengerSouls_Busi;
	private java.util.List<au.com.leonardo.poc.sms_test.Manifest> manifest;

	private java.lang.String gate;

	public ThisFlight() {
	}

	public java.lang.Integer getPassengerSouls_Econ() {
		return this.passengerSouls_Econ;
	}

	public void setPassengerSouls_Econ(java.lang.Integer passengerSouls_Econ) {
		this.passengerSouls_Econ = passengerSouls_Econ;
	}

	public java.lang.Integer getPassengerSouls_Busi() {
		return this.passengerSouls_Busi;
	}

	public void setPassengerSouls_Busi(java.lang.Integer passengerSouls_Busi) {
		this.passengerSouls_Busi = passengerSouls_Busi;
	}

	public java.util.List<au.com.leonardo.poc.sms_test.Manifest> getManifest() {
		return this.manifest;
	}

	public void setManifest(
			java.util.List<au.com.leonardo.poc.sms_test.Manifest> manifest) {
		this.manifest = manifest;
	}

	public java.lang.String getGate() {
		return this.gate;
	}

	public void setGate(java.lang.String gate) {
		this.gate = gate;
	}

	public ThisFlight(java.lang.Integer passengerSouls_Econ,
			java.lang.Integer passengerSouls_Busi,
			java.util.List<au.com.leonardo.poc.sms_test.Manifest> manifest,
			java.lang.String gate) {
		this.passengerSouls_Econ = passengerSouls_Econ;
		this.passengerSouls_Busi = passengerSouls_Busi;
		this.manifest = manifest;
		this.gate = gate;
	}

}